spring:
  application:
    name: msgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/msmarvel-realm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://msmarvel-user:arvmelsm@localhost:8761/eureka
#  instance:
#    hostname: msgateway
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

